# Generated by Django 2.0.5 on 2018-06-05 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20180605_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular answer across whole library', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('answers', models.ManyToManyField(help_text='Select possible answers for questions.', to='quizzes.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(help_text='Select questions for the quiz', to='quizzes.Question'),
        ),
    ]
