# Generated by Django 2.0.5 on 2018-06-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20180605_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title',
            new_name='name',
        ),
    ]
