# Generated by Django 2.0.5 on 2018-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20180606_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='theme',
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.ManyToManyField(help_text='Select quiz theme', to='quizzes.Theme'),
        ),
    ]
